# How many letters deep should we go?
depth = 7
# Get the words
import requests
url = "https://raw.githubusercontent.com/dwyl/english-words/master/words.txt"
response = requests.get(url)

used_words = 'ABACK ABASE ABATE ABBEY ABOUT ABOVE ABYSS ACRID ACTOR ACUTE ADMIT ADOBE ADOPT ADORE ADULT AGAIN AGAPE AGATE AGENT AGILE AGLOW AGONY AGREE AHEAD ALBUM ALIEN ALIKE ALLOW ALOFT ALONE ALOUD ALPHA ALTAR ALTER AMBER AMISS AMPLE ANGEL ANGER ANGRY ANODE ANTIC AORTA APHID APPLE APPLY APRON APTLY ARBOR ARDOR ARGUE AROMA ASIDE ASKEW ASSET ATOLL ATONE AUDIO AUDIT AVAIL AVERT AWAIT AWAKE AWFUL AXIOM AZURE BADGE BADLY BAGEL BAKER BALSA BANAL BARGE BASIC BATHE BATON BATTY BAYOU BEACH BEADY BEAST BEEFY BEGET BEGIN BEING BELCH BELIE BELLY BELOW BENCH BERET BERTH BESET BINGE BIOME BIRCH BIRTH BLACK BLAME BLAND BLEAK BLEED BLEEP BLOKE BLOWN BLUFF BLURB BLURT BLUSH BOOBY BOOST BOOZE BOOZY BORAX BOUGH BRAID BRAKE BRASH BRAVE BREAD BREAK BRIAR BRIBE BRIDE BRINE BRING BRINK BRISK BROKE BROOK BROOM BRUSH BUGGY BULLY BUNCH BURLY CACAO CACHE CANDY CANNY CANOE CAPER CARAT CARGO CARRY CAROL CATCH CATER CAULK CAUSE CEDAR CHAFE CHAMP CHANT CHARD CHARM CHART CHEAT CHEEK CHEST CHIEF CHILL CHIME CHOIR CHOKE CHORD CHUNK CHUTE CIDER CIGAR CINCH CIRCA CIVIC CLASS CLEAN CLEAR CLERK CLICK CLING CLOCK CLOSE CLOTH CLOWN CLUCK COACH COAST COCOA COLON COMET COMMA CONDO CONIC CORNY COULD COUNT COVET COWER COYLY CRAMP CRANE CRANK CRASS CRATE CRAVE CRAZE CRAZY CREAK CREDO CREPT CRIME CRIMP CROAK CRONE CROSS CRUMB CRUST CURLY CYNIC DADDY DANCE DANDY DEATH DEBUG DELTA DELVE DENIM DEPOT DEPTH DIGIT DINER DISCO DITTO DODGE DONOR DONUT DOUBT DOWRY DOZEN DRAIN DREAM DRINK DRIVE DROLL DROOP DUCHY DUTCH DUVET DWARF DWELL DWELT EARTH EGRET EJECT ELDER ELOPE ELUDE EMAIL EMPTY ENEMA ENJOY ENNUI ENTER EPOCH EPOXY EQUAL ERODE ERROR ESSAY ETHIC ETHOS EVADE EVERY EXACT EXCEL EXERT EXIST EXTRA EXULT FARCE FAULT FAVOR FEAST FEIGN FERRY FEWER FIELD FIEND FIFTY FINER FIRST FISHY FIXER FJORD FLAIL FLAIR FLANK FLARE FLASK FLESH FLICK FLING FLIRT FLOAT FLOCK FLOOD FLOOR FLORA FLOSS FLOUT FLUFF FLUME FLYER FOCAL FOCUS FOGGY FOLLY FORAY FORGE FORGO FORTH FOUND FOYER FRAME FRANK FRESH FROCK FRONT FROST FROTH FROZE FUNGI GAMER GAMMA GAUDY GAUZE GAWKY GECKO GHOUL GIANT GIDDY GIRTH GIVEN GLASS GLAZE GLEAN GLOAT GLOOM GLORY GLOVE GLYPH GNASH GOLEM GONER GOOSE GORGE GOUGE GRADE GRAIL GRAND GRAPH GRATE GREAT GREEN GREET GRIEF GRIME GRIMY GRIPE GROIN GROUP GROUT GROVE GROWL GRUEL GUANO GUARD GUEST GUIDE GUILD GULLY GUPPY HAIRY HAPPY HATCH HATER HAVOC HEADY HEART HEATH HEIST HELIX HELLO HERON HINGE HOARD HOBBY HOMER HORDE HORSE HOTEL HOUND HOWDY HUMAN HUMID HUMOR HUMPH HUNKY HURRY HUTCH HYPER IGLOO IMPEL INANE INDEX INEPT INERT INFER INPUT INTER IONIC IRATE IRONY ISLET ITCHY IVORY JAUNT JAZZY JOKER JOUST JUDGE KARMA KAYAK KAZOO KEBAB KHAKI KIOSK KNEEL KNELT KNOCK KNOLL KOALA LABEL LABOR LAPEL LAPSE LARVA LATTE LAYER LEAFY LEAKY LEAPT LEASH LEAVE LEDGE LEERY LEMON LIBEL LIGHT LILAC LIMIT LINEN LIVER LOCUS LOFTY LOGIC LOOPY LOSER LOVER LOWLY LOYAL LUCKY LUNAR LUSTY LYING MADAM MAGIC MAGMA MAIZE MAJOR MANIA MANLY MANOR MAPLE MARCH MARRY MARSH MASON MASSE MATEY MAXIM MAYBE MEALY MEANT MEDAL MERCY MERIT MERRY METAL METRO MIDGE MIDST MIMIC MINCE MODEL MOIST MOLAR MONEY MONTH MOOSE MOSSY MOTOR MOTTO MOULT MOUNT MOURN MOUSE MOVIE MUCKY MUMMY MUSIC NAIVE NANNY NASTY NATAL NAVAL NEEDY NIGHT NINJA NINTH NOBLE NOISE NYMPH OCCUR OCEAN OFFAL OLDER OLIVE ONION ONSET OPERA OTHER OUGHT OUTDO OXIDE PANEL PANIC PAPER PARER PARRY PARTY PATTY PAUSE PEACE PEACH PERCH PERKY PHASE PHONY PHOTO PIANO PICKY PIETY PILOT PINEY PINKY PINTO PIQUE PITHY PIXEL PIXIE PLANK PLANT PLATE PLAZA PLEAT PLUCK PLUNK POINT POISE POKER POLKA POLYP POUND POWER PRICK PRIDE PRIME PRIMO PRINT PRIZE PROBE PROVE PROXY PULPY PURGE QUALM QUART QUEEN QUERY QUEST QUEUE QUICK QUIET QUIRK QUOTE RADIO RAINY RAMEN RANCH RANGE RATIO RAYON REACT REBUS REBUT RECAP REGAL RENEW REPAY RESIN RETCH RETRO RETRY REVEL RHINO RHYME RIGHT RIPER RIVAL ROBIN ROBOT ROCKY RODEO ROGUE ROOMY ROUGE ROUND ROUSE ROYAL RUDDY RUDER RUPEE RUSTY SAINT SALAD SALSA SASSY SAUTE SCALD SCARE SCARF SCOLD SCOPE SCORN SCOUR SCOUT SCRAP SCRUB SEDAN SEEDY SERVE SEVER SHAKE SHALL SHAME SHARD SHAWL SHINE SHIRE SHIRK SHORN SHOWN SHOWY SHRUB SHRUG SHYLY SIEGE SIGHT SISSY SKILL SKIMP SKIRT SKUNK SLATE SLEEK SLOSH SLOTH SLUMP SLUNG SMART SMASH SMEAR SMELT SMILE SMIRK SMITE SNACK SNAFU SNAIL SNAKY SNARE SNARL SNEAK SNOUT SOGGY SOLAR SOLID SOLVE SONIC SOUND SOWER SPACE SPADE SPELL SPEND SPICE SPICY SPIEL SPIKE SPILL SPIRE SPLAT SPOKE SPRAY SPURT SQUAD SQUAT STAFF STAGE STAID STAIR STALE STAND START STEAD STEED STEIN STICK STING STINK STOCK STOMP STONE STOOL STORE STORY STOUT STOVE STRAP STRAW STUDY STYLE SUGAR SULKY SURER SURLY SUSHI SWEAT SWEEP SWEET SWILL SWINE SWIRL SYRUP TACIT TANGY TAPER TAPIR TARDY TASTE TASTY TAUNT TAWNY TEASE TEMPO TENTH TEPID THEIR THEME THERE THIEF THINK THIRD THORN THOSE THROW THUMB THUMP THYME TIARA TIBIA TIGER TILDE TIPSY TODAY TONIC TOPAZ TORSO TOTEM TOUGH TOXIC TRACE TRACT TRADE TRAIN TRAIT TRASH TRAWL TREAT TREND TRIAD TRICE TRITE TROLL TROPE TROVE TRUSS TRUST TRUTH TRYST TWANG TWEED TWICE TWINE ULCER ULTRA UNCLE UNDER UNDUE UNFED UNFIT UNIFY UNITE UNLIT UNMET UNTIE UNTIL UNZIP UPSET USAGE USHER USING USUAL USURP UTTER VAGUE VALET VALID VENOM VERVE VIGOR VIOLA VIRAL VITAL VIVID VODKA VOICE VOTER VOUCH WACKY WALTZ WASTE WATCH WEARY WEDGE WHACK WHALE WHEEL WHELP WHERE WHIFF WHILE WHINE WHIRL WHISK WHOOP WINCE WINDY WOKEN WOOER WORDY WORLD WORRY WORSE WOVEN WRATH WRITE WRONG WROTE WRUNG YACHT YEARN YIELD YOUTH ZESTY'.lower().split(' ')

# Parse the words into a list
response.encoding = response.apparent_encoding
words = response.text.split('\n')

# Filter the words
import re
five_letter_words = []
for word in words:
    filtered_word = re.sub(r'[^a-zA-Z]', '', word)
    if len(str(filtered_word)) == 5 and filtered_word not in five_letter_words:
        five_letter_words.append(filtered_word.lower())

# Count each letter

frequency_table = {
    "a": 0,
    "b": 0,
    "c": 0,
    "d": 0,
    "e": 0,
    "f": 0,
    "g": 0,
    "h": 0,
    "i": 0,
    "j": 0,
    "k": 0,
    "l": 0,
    "m": 0,
    "n": 0,
    "o": 0,
    "p": 0,
    "q": 0,
    "r": 0,
    "s": 0,
    "t": 0,
    "u": 0,
    "v": 0,
    "w": 0,
    "x": 0,
    "y": 0,
    "z": 0
}

for word in five_letter_words:
    for key in frequency_table:
        if key in word:
            frequency_table[key] = frequency_table[key] +1

# Make table callable for the score_word function
final_table = []
for key in frequency_table:
    final_table.append((key, frequency_table[key]))

# Score each word
winners = []

def score_word(word):
    score = 0
    for x, y in final_table[:depth]:
        if x in word:
            score = score + 1
    return score

def check_anagram(word1, word2):
    if(sorted(word1) == sorted(word2)):
        return True
    else:
        return False
    
for word in five_letter_words:
    word_score = score_word(word)
    if word_score >= 5:
        if len(winners) == 0:
            winners.append(word)
        else:
            for winner in winners:
                result = check_anagram(word, winner)
                if not result and word not in winners and word not in used_words:
                    winners.append(word)

print(winners)
